### ISSUE TITLE
Any invocation fails with `list index out of range`

### ISSUE THREAD

**Issue by agross** [JavaWiz1/kodi-cli#3]
Hi, 

I am trying to get `kodi-cli` to run on macOS. Regardless of the arguments passed or `$PWD`, this is always the result:

```
$ kodi-cli --help
Traceback (most recent call last):
  File "/opt/homebrew/bin/kodi-cli", line 5, in <module>
    from kodi_cli import main
  File "/opt/homebrew/lib/python3.11/site-packages/kodi_cli.py", line 18, in <module>
    __version__ = ver_info.get_version("kodi-cli")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/version.py", line 21, in get_version
    __version__ = _get_pytoml_version(pkg_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/version.py", line 34, in _get_pytoml_version
    toml_dir = [p for p in current_dir.parents if p.parts[-1]==pkg_name][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by JavaWiz1** [comment]
Sorry, been away for a bit, I'll take a look @ this sometime over the next few days...

**Comment by JavaWiz1** [comment]
Bumped up to v0.2.1, I think this is fixed can you try again and reply back with resutls.

Thanks.

**Comment by agross** [comment]
Thanks, I installed 0.2.1 and now I can see the help screen!
